---
- name: Deploy a jar file
  hosts: ubu18
  tasks:
    - name: Copy jar file to home directory
      copy:
        src: /home/vibhor/calculatorDevOps-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: ~/
